module.exports = { data: [
  {"id":"542","value":"Afghanistan"},
  {"id":"242","value":"Albania"},
  {"id":"443","value":"Algeria"},
  {"id":"667","value":"American Samoa"},
  {"id":"156","value":"Andorra"},
  {"id":"446","value":"Angola"},
  {"id":"830","value":"Anguilla"},
  {"id":"832","value":"Antigua and Barbuda"},
  {"id":"744","value":"Argentina"},
  {"id":"280","value":"Armenia"},
  {"id":"877","value":"Aruba"},
  {"id":"614","value":"Australia"},
  {"id":"143","value":"Austria"},
  {"id":"281","value":"Azerbaijan"},
  {"id":"813","value":"Bahamas"},
  {"id":"313","value":"Bahrain"},
  {"id":"512","value":"Bangladesh"},
  {"id":"822","value":"Barbados"},
  {"id":"285","value":"Belarus"},
  {"id":"144","value":"Belgium"},
  {"id":"817","value":"Belize"},
  {"id":"455","value":"Benin"},
  {"id":"815","value":"Bermuda"},
  {"id":"544","value":"Bhutan"},
  {"id":"747","value":"Bolivia"},
  {"id":"872","value":"Bonaire, Sint Eustatius and Saba"},
  {"id":"278","value":"Bosnia and Herzegovina"},
  {"id":"752","value":"Brazil"},
  {"id":"434","value":"British Indian Ocean Territory"},
  {"id":"525","value":"Brunei Darussalam"},
  {"id":"245","value":"Bulgaria"},
  {"id":"457","value":"Burkina Faso"},
  {"id":"548","value":"Cambodia"},
  {"id":"447","value":"Cameroon"},
  {"id":"477","value":"Cape Verde"},
  {"id":"825","value":"Cayman Islands"},
  {"id":"451","value":"Chad"},
  {"id":"755","value":"Chile"},
  {"id":"553","value":"China"},
  {"id":"615","value":"Christmas Island"},
  {"id":"610","value":"Cocos (Keeling) Islands"},
  {"id":"758","value":"Colombia"},
  {"id":"460","value":"Comoros"},
  {"id":"452","value":"Congo"},
  {"id":"449","value":"Congo, Democratic Republic"},
  {"id":"621","value":"Cook Islands"},
  {"id":"845","value":"Costa Rica"},
  {"id":"290","value":"Croatia"},
  {"id":"848","value":"Cuba"},
  {"id":"870","value":"Curaçao"},
  {"id":"316","value":"Cyprus"},
  {"id":"247","value":"Czech Republic"},
  {"id":"246","value":"Czechoslovakia"},
  {"id":"149","value":"Denmark"},
  {"id":"459","value":"Djibouti"},
  {"id":"833","value":"Dominica"},
  {"id":"855","value":"Dominican Republic"},
  {"id":"763","value":"Ecuador"},
  {"id":"385","value":"Egypt"},
  {"id":"480","value":"Equatorial Guinea"},
  {"id":"282","value":"Estonia"},
  {"id":"150","value":"Faeroe Islands"},
  {"id":"617","value":"Fiji"},
  {"id":"153","value":"Finland"},
  {"id":"287","value":"Former USSR"},
  {"id":"154","value":"France"},
  {"id":"654","value":"French Polynesia"},
  {"id":"461","value":"French Southern Territories"},
  {"id":"463","value":"Gabon"},
  {"id":"413","value":"Gambia"},
  {"id":"291","value":"Georgia"},
  {"id":"155","value":"Germany"},
  {"id":"258","value":"Germany, East"},
  {"id":"414","value":"Ghana"},
  {"id":"115","value":"Gibraltar"},
  {"id":"159","value":"Greece"},
  {"id":"3","value":"Greenland"},
  {"id":"834","value":"Grenada"},
  {"id":"862","value":"Guadeloupe"},
  {"id":"666","value":"Guam"},
  {"id":"864","value":"Guatemala"},
  {"id":"465","value":"Guinea"},
  {"id":"475","value":"Guinea-Bissau"},
  {"id":"716","value":"Guyana"},
  {"id":"867","value":"Haiti"},
  {"id":"616","value":"Heard Is. and McDonald Islands"},
  {"id":"869","value":"Honduras"},
  {"id":"516","value":"Hong Kong"},
  {"id":"262","value":"Hungary"},
  {"id":"163","value":"Iceland"},
  {"id":"519","value":"India"},
  {"id":"556","value":"Indonesia"},
  {"id":"347","value":"Iran"},
  {"id":"117","value":"Ireland, Republic of (EIRE)"},
  {"id":"355","value":"Israel"},
  {"id":"167","value":"Italy"},
  {"id":"466","value":"Ivory Coast"},
  {"id":"824","value":"Jamaica"},
  {"id":"559","value":"Japan"},
  {"id":"358","value":"Jordan"},
  {"id":"292","value":"Kazakhstan"},
  {"id":"415","value":"Kenya"},
  {"id":"625","value":"Kiribati"},
  {"id":"563","value":"Korea, North"},
  {"id":"564","value":"Korea, South"},
  {"id":"359","value":"Kuwait"},
  {"id":"293","value":"Kyrgyzstan"},
  {"id":"549","value":"Laos"},
  {"id":"283","value":"Latvia"},
  {"id":"363","value":"Lebanon"},
  {"id":"431","value":"Lesotho"},
  {"id":"468","value":"Liberia"},
  {"id":"284","value":"Lithuania"},
  {"id":"170","value":"Luxembourg"},
  {"id":"575","value":"Macao"},
  {"id":"276","value":"Macedonia (FYROM)"},
  {"id":"469","value":"Madagascar"},
  {"id":"416","value":"Malawi"},
  {"id":"524","value":"Malaysia"},
  {"id":"514","value":"Maldives"},
  {"id":"119","value":"Malta"},
  {"id":"863","value":"Martinique"},
  {"id":"472","value":"Mauritania"},
  {"id":"417","value":"Mauritius"},
  {"id":"874","value":"Mexico"},
  {"id":"294","value":"Moldova, Republic of"},
  {"id":"552","value":"Mongolia"},
  {"id":"275","value":"Montenegro"},
  {"id":"829","value":"Montserrat"},
  {"id":"473","value":"Morocco"},
  {"id":"476","value":"Mozambique"},
  {"id":"545","value":"Myanmar"},
  {"id":"420","value":"Namibia"},
  {"id":"611","value":"Nauru"},
  {"id":"565","value":"Nepal"},
  {"id":"173","value":"Netherlands"},
  {"id":"876","value":"Netherlands Antilles"},
  {"id":"653","value":"New Caledonia"},
  {"id":"622","value":"New Zealand"},
  {"id":"879","value":"Nicaragua"},
  {"id":"454","value":"Niger"},
  {"id":"418","value":"Nigeria"},
  {"id":"612","value":"Norfolk Island"},
  {"id":"176","value":"Norway"},
  {"id":"368","value":"Oman"},
  {"id":"527","value":"Pakistan"},
  {"id":"883","value":"Panama"},
  {"id":"613","value":"Papua New Guinea"},
  {"id":"769","value":"Paraguay"},
  {"id":"774","value":"Peru"},
  {"id":"567","value":"Philippines"},
  {"id":"626","value":"Pitcairn"},
  {"id":"277","value":"Poland"},
  {"id":"178","value":"Portugal"},
  {"id":"886","value":"Puerto Rico"},
  {"id":"323","value":"Qatar"},
  {"id":"279","value":"Romania"},
  {"id":"295","value":"Russian Federation"},
  {"id":"456","value":"Rwanda"},
  {"id":"433","value":"Saint Helena"},
  {"id":"831","value":"Saint Kitts and Nevis"},
  {"id":"835","value":"Saint Lucia"},
  {"id":"6","value":"Saint Pierre and Miquelon"},
  {"id":"836","value":"Saint Vincent & the Grenadines"},
  {"id":"628","value":"Samoa"},
  {"id":"478","value":"Sao Tome and Principe"},
  {"id":"369","value":"Saudi Arabia"},
  {"id":"482","value":"Senegal"},
  {"id":"274","value":"Serbia"},
  {"id":"288","value":"Serbia and Montenegro"},
  {"id":"435","value":"Seychelles"},
  {"id":"423","value":"Sierra Leone"},
  {"id":"528","value":"Singapore"},
  {"id":"871","value":"Sint Maarten"},
  {"id":"248","value":"Slovakia"},
  {"id":"289","value":"Slovenia"},
  {"id":"623","value":"Solomon Islands"},
  {"id":"374","value":"Somalia"},
  {"id":"419","value":"South Africa"},
  {"id":"378","value":"South Sudan"},
  {"id":"182","value":"Spain"},
  {"id":"513","value":"Sri Lanka"},
  {"id":"777","value":"Suriname"},
  {"id":"432","value":"Swaziland"},
  {"id":"185","value":"Sweden"},
  {"id":"186","value":"Switzerland"},
  {"id":"379","value":"Syria"},
  {"id":"578","value":"Taiwan"},
  {"id":"296","value":"Tajikistan"},
  {"id":"425","value":"Tanzania, United Republic of"},
  {"id":"583","value":"Thailand"},
  {"id":"557","value":"Timor-Leste"},
  {"id":"486","value":"Togo"},
  {"id":"619","value":"Tokelau"},
  {"id":"627","value":"Tonga"},
  {"id":"828","value":"Trinidad and Tobago"},
  {"id":"487","value":"Tunisia"},
  {"id":"382","value":"Turkey"},
  {"id":"297","value":"Turkmenistan"},
  {"id":"827","value":"Turks and Caicos Islands"},
  {"id":"668","value":"U.S. Minor Outlying Islands"},
  {"id":"426","value":"Uganda"},
  {"id":"286","value":"Ukraine"},
  {"id":"328","value":"United Arab Emirates"},
  {"id":"101","value":"United Kingdom"},
  {"id":"9","value":"United States"},
  {"id":"782","value":"Uruguay"},
  {"id":"298","value":"Uzbekistan"},
  {"id":"652","value":"Vanuatu"},
  {"id":"785","value":"Venezuela"},
  {"id":"586","value":"Viet Nam"},
  {"id":"823","value":"Virgin Islands, British"},
  {"id":"651","value":"Wallis and Futuna"},
  {"id":"999","value":"World"},
  {"id":"422","value":"Zimbabwe"},
  {"id":"1004","value":"Alabama"},
  {"id":"1003","value":"Alaska"},
  {"id":"1006","value":"Arizona"},
  {"id":"1005","value":"Arkansas"},
  {"id":"1007","value":"California"},
  {"id":"1008","value":"Colorado"},
  {"id":"1009","value":"Connecticut"},
  {"id":"1011","value":"Delaware"},
  {"id":"1010","value":"Dist. of Columbia"},
  {"id":"1012","value":"Florida"},
  {"id":"1013","value":"Georgia"},
  {"id":"1014","value":"Hawaii"},
  {"id":"1016","value":"Idaho"},
  {"id":"1017","value":"Illinois"},
  {"id":"1018","value":"Indiana"},
  {"id":"1015","value":"Iowa"},
  {"id":"1019","value":"Kansas"},
  {"id":"1020","value":"Kentucky"},
  {"id":"1021","value":"Louisiana"},
  {"id":"1024","value":"Maine"},
  {"id":"1023","value":"Maryland"},
  {"id":"1022","value":"Massachusetts"},
  {"id":"1025","value":"Michigan"},
  {"id":"1026","value":"Minnesota"},
  {"id":"1028","value":"Mississippi"},
  {"id":"1027","value":"Missouri"},
  {"id":"1029","value":"Montana"},
  {"id":"1032","value":"Nebraska"},
  {"id":"1036","value":"Nevada"},
  {"id":"1033","value":"New Hampshire"},
  {"id":"1034","value":"New Jersey"},
  {"id":"1035","value":"New Mexico"},
  {"id":"1037","value":"New York"},
  {"id":"1000","value":"Non USA"},
  {"id":"1030","value":"North Carolina"},
  {"id":"1031","value":"North Dakota"},
  {"id":"1038","value":"Ohio"},
  {"id":"1039","value":"Oklahoma"},
  {"id":"1040","value":"Oregon"},
  {"id":"1002","value":"Other States"},
  {"id":"1041","value":"Pennsylvania"},
  {"id":"1042","value":"Puerto Rico"},
  {"id":"1043","value":"Rhode Island"},
  {"id":"1044","value":"South Carolina"},
  {"id":"1045","value":"South Dakota"},
  {"id":"1046","value":"Tennessee"},
  {"id":"1047","value":"Texas"},
  {"id":"1050","value":"U.S. Virgin Is."},
  {"id":"1048","value":"Utah"},
  {"id":"1051","value":"Vermont"},
  {"id":"1049","value":"Virginia"},
  {"id":"1052","value":"Washington, state"},
  {"id":"1054","value":"West Virginia"},
  {"id":"1053","value":"Wisconsin"},
  {"id":"1055","value":"Wyoming"}
]};
